import { UserRole } from "@/db/types";
import { Permission as P } from "./permissions";

type Role = (typeof UserRole)[number];
type RolePermissions = Record<Role, ReadonlySet<P>>;

export const RolePermissions: RolePermissions = {
    admin: new Set<P>([
        P.AUTH_ME,
        P.AUTH_LOGOUT,
        P.AUTH_REFRESH,

        P.USERS_LIST,
        P.USERS_READ_SELF,
        P.USERS_READ_ANY,
        P.USERS_CREATE,
        P.USERS_UPDATE_SELF,
        P.USERS_UPDATE_ANY,
        P.USERS_DELETE,
        P.USERS_DEACTIVATE,

        P.DOCTORS_LIST,
        P.DOCTORS_READ_SELF,
        P.DOCTORS_READ_ANY,
        P.DOCTORS_CREATE,
        P.DOCTORS_UPDATE_SELF,
        P.DOCTORS_UPDATE_ANY,
        P.DOCTORS_DELETE,
        P.DOCTORS_SCHEDULE_READ_SELF,
        P.DOCTORS_SCHEDULE_READ_ANY,
        P.DOCTORS_SCHEDULE_UPDATE_SELF,
        P.DOCTORS_SCHEDULE_UPDATE_ANY,

        P.PATIENTS_LIST,
        P.PATIENTS_READ_SELF,
        P.PATIENTS_READ_ANY,
        P.PATIENTS_CREATE,
        P.PATIENTS_UPDATE_SELF,
        P.PATIENTS_UPDATE_ANY,
        P.PATIENTS_DELETE,
        P.PATIENTS_RECORDS_READ_SELF,
        P.PATIENTS_RECORDS_READ_ANY,
        P.PATIENTS_RECORDS_CREATE,
        P.PATIENTS_DOCUMENTS_UPLOAD_SELF,
        P.PATIENTS_DOCUMENTS_UPLOAD_ANY,
        P.PATIENTS_DOCUMENTS_READ_SELF,
        P.PATIENTS_DOCUMENTS_READ_ANY,

        P.APPOINTMENTS_LIST_SELF,
        P.APPOINTMENTS_LIST_ANY,
        P.APPOINTMENTS_READ_SELF,
        P.APPOINTMENTS_READ_ANY,
        P.APPOINTMENTS_CREATE,
        P.APPOINTMENTS_UPDATE_SELF,
        P.APPOINTMENTS_UPDATE_ANY,
        P.APPOINTMENTS_CANCEL_SELF,
        P.APPOINTMENTS_CANCEL_ANY,

        P.PRESCRIPTIONS_LIST_SELF,
        P.PRESCRIPTIONS_LIST_ANY,
        P.PRESCRIPTIONS_READ_SELF,
        P.PRESCRIPTIONS_READ_ANY,
        P.PRESCRIPTIONS_CREATE,
        P.PRESCRIPTIONS_UPDATE,

        P.PHARMACY_LIST,
        P.PHARMACY_READ,
        P.PHARMACY_CREATE,
        P.PHARMACY_UPDATE,
        P.PHARMACY_DELETE,

        P.ORDERS_LIST_SELF,
        P.ORDERS_LIST_ANY,
        P.ORDERS_READ_SELF,
        P.ORDERS_READ_ANY,
        P.ORDERS_CREATE,
        P.ORDERS_UPDATE_ANY,

        P.PAYMENTS_LIST_SELF,
        P.PAYMENTS_LIST_ANY,
        P.PAYMENTS_READ_SELF,
        P.PAYMENTS_READ_ANY,
        P.PAYMENTS_CREATE,

        P.INVOICES_LIST_SELF,
        P.INVOICES_LIST_ANY,
        P.INVOICES_READ_SELF,
        P.INVOICES_READ_ANY,
        P.INVOICES_CREATE,

        P.REFUNDS_LIST_SELF,
        P.REFUNDS_LIST_ANY,
        P.REFUNDS_READ_SELF,
        P.REFUNDS_READ_ANY,
        P.REFUNDS_CREATE,
        P.REFUNDS_APPROVE,

        P.DEPARTMENTS_LIST,
        P.DEPARTMENTS_READ,
        P.DEPARTMENTS_CREATE,
        P.DEPARTMENTS_UPDATE,
        P.DEPARTMENTS_DELETE,

        P.SUPPORT_LIST_SELF,
        P.SUPPORT_LIST_ANY,
        P.SUPPORT_READ_SELF,
        P.SUPPORT_READ_ANY,
        P.SUPPORT_CREATE,
        P.SUPPORT_UPDATE_ANY,
        P.SUPPORT_CLOSE,

        P.CONSULTATIONS_LIST_SELF,
        P.CONSULTATIONS_LIST_ANY,
        P.CONSULTATIONS_READ_SELF,
        P.CONSULTATIONS_READ_ANY,
        P.CONSULTATIONS_CREATE,
        P.CONSULTATIONS_UPDATE_SELF,
        P.CONSULTATIONS_UPDATE_ANY,

        P.LEAVE_LIST_SELF,
        P.LEAVE_LIST_ANY,
        P.LEAVE_READ_SELF,
        P.LEAVE_READ_ANY,
        P.LEAVE_CREATE,
        P.LEAVE_APPROVE,

        P.ADMIN_DASHBOARD,
        P.ADMIN_SETTINGS,
        P.ADMIN_AUDIT_LOG,
    ]),

    doctor: new Set<P>([
        P.AUTH_ME,
        P.AUTH_LOGOUT,
        P.AUTH_REFRESH,

        P.USERS_READ_SELF,
        P.USERS_UPDATE_SELF,

        P.DOCTORS_LIST,
        P.DOCTORS_READ_SELF,
        P.DOCTORS_READ_ANY,
        P.DOCTORS_UPDATE_SELF,
        P.DOCTORS_SCHEDULE_READ_SELF,
        P.DOCTORS_SCHEDULE_READ_ANY,
        P.DOCTORS_SCHEDULE_UPDATE_SELF,

        P.PATIENTS_LIST,
        P.PATIENTS_READ_ANY,
        P.PATIENTS_RECORDS_READ_ANY,
        P.PATIENTS_RECORDS_CREATE,
        P.PATIENTS_DOCUMENTS_UPLOAD_ANY,
        P.PATIENTS_DOCUMENTS_READ_ANY,

        P.APPOINTMENTS_LIST_SELF,
        P.APPOINTMENTS_READ_SELF,
        P.APPOINTMENTS_READ_ANY,
        P.APPOINTMENTS_UPDATE_SELF,
        P.APPOINTMENTS_CANCEL_SELF,

        P.PRESCRIPTIONS_LIST_SELF,
        P.PRESCRIPTIONS_LIST_ANY,
        P.PRESCRIPTIONS_READ_SELF,
        P.PRESCRIPTIONS_READ_ANY,
        P.PRESCRIPTIONS_CREATE,
        P.PRESCRIPTIONS_UPDATE,

        P.CONSULTATIONS_LIST_SELF,
        P.CONSULTATIONS_READ_SELF,
        P.CONSULTATIONS_READ_ANY,
        P.CONSULTATIONS_CREATE,
        P.CONSULTATIONS_UPDATE_SELF,

        P.DEPARTMENTS_LIST,
        P.DEPARTMENTS_READ,

        P.SUPPORT_LIST_SELF,
        P.SUPPORT_READ_SELF,
        P.SUPPORT_CREATE,

        P.LEAVE_LIST_SELF,
        P.LEAVE_READ_SELF,
        P.LEAVE_CREATE,

        P.PHARMACY_LIST,
        P.PHARMACY_READ,
    ]),

    patient: new Set<P>([
        P.AUTH_ME,
        P.AUTH_LOGOUT,
        P.AUTH_REFRESH,

        P.USERS_READ_SELF,
        P.USERS_UPDATE_SELF,

        P.PATIENTS_READ_SELF,
        P.PATIENTS_UPDATE_SELF,
        P.PATIENTS_RECORDS_READ_SELF,
        P.PATIENTS_DOCUMENTS_UPLOAD_SELF,
        P.PATIENTS_DOCUMENTS_READ_SELF,

        P.APPOINTMENTS_LIST_SELF,
        P.APPOINTMENTS_READ_SELF,
        P.APPOINTMENTS_CREATE,
        P.APPOINTMENTS_CANCEL_SELF,

        P.PRESCRIPTIONS_LIST_SELF,
        P.PRESCRIPTIONS_READ_SELF,

        P.ORDERS_LIST_SELF,
        P.ORDERS_READ_SELF,
        P.ORDERS_CREATE,

        P.PAYMENTS_LIST_SELF,
        P.PAYMENTS_READ_SELF,
        P.PAYMENTS_CREATE,

        P.INVOICES_LIST_SELF,
        P.INVOICES_READ_SELF,

        P.REFUNDS_LIST_SELF,
        P.REFUNDS_READ_SELF,
        P.REFUNDS_CREATE,

        P.DEPARTMENTS_LIST,
        P.DEPARTMENTS_READ,
        P.DOCTORS_LIST,
        P.DOCTORS_READ_ANY,
        P.DOCTORS_SCHEDULE_READ_ANY,

        P.PHARMACY_LIST,
        P.PHARMACY_READ,

        P.SUPPORT_LIST_SELF,
        P.SUPPORT_READ_SELF,
        P.SUPPORT_CREATE,

        P.CONSULTATIONS_LIST_SELF,
        P.CONSULTATIONS_READ_SELF,
    ]),
};
